// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using U7Fact.Data;

#nullable disable

namespace U7Fact.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250211173351_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("U7Fact.Model.Factuur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Betalingstermijn")
                        .HasColumnType("int");

                    b.Property<DateTime>("FactuurDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("FactuurNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterneNotitie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KlantId")
                        .HasColumnType("int");

                    b.Property<string>("LosseBijlage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OfferteId")
                        .HasColumnType("int");

                    b.Property<string>("Referentie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerzendDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Verzendmetode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.HasIndex("OfferteId");

                    b.ToTable("Facturen");
                });

            modelBuilder.Entity("U7Fact.Model.Klant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aanspreking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AansprekingContactpersoon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Achtervoegsel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bedrijfsnaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BtwNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraAanspreking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraAchternaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraGsmnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraTelefoonnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraVoornaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gemeente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gsmnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Huisnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterneNotitie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KboNummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KlantType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Klantnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Land")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Straatnaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefoonnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Klantnummer")
                        .IsUnique();

                    b.ToTable("Klanten");
                });

            modelBuilder.Entity("U7Fact.Model.Offerte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Geldigheidsduur")
                        .HasColumnType("int");

                    b.Property<string>("InterneNotitie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KlantId")
                        .HasColumnType("int");

                    b.Property<string>("LosseBijlage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OfferteDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Referentie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerzendDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Verzendmetode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.ToTable("Offertes");
                });

            modelBuilder.Entity("U7Fact.Model.Factuur", b =>
                {
                    b.HasOne("U7Fact.Model.Klant", "Klant")
                        .WithMany("Facturen")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("U7Fact.Model.Offerte", "Offerte")
                        .WithMany()
                        .HasForeignKey("OfferteId");

                    b.Navigation("Klant");

                    b.Navigation("Offerte");
                });

            modelBuilder.Entity("U7Fact.Model.Offerte", b =>
                {
                    b.HasOne("U7Fact.Model.Klant", "Klant")
                        .WithMany("Offertes")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Klant");
                });

            modelBuilder.Entity("U7Fact.Model.Klant", b =>
                {
                    b.Navigation("Facturen");

                    b.Navigation("Offertes");
                });
#pragma warning restore 612, 618
        }
    }
}
